name: Update Helm Chart Repository

on:
   push:
      branches: [main]
   workflow_dispatch:

jobs:
    update-values:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Helm Repo
          uses: actions/checkout@v4
          with:
            repository: arunkaousula9421/helm-chart-repo
            token: ${{ secrets.REPO_HELM_PAT }}
            ref: main

        - name: Update tag and create PR
          env:
            GH_TOKEN: ${{ secrets.REPO_HELM_PAT }}
          run: |
            TAG="v${{ github.run_number }}"
            BRANCH="update/${TAG}"
            sed -i "s|tag:.*|tag: \"${TAG}\"|" values.yaml

            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

            if git diff --quiet values.yaml; then
              echo "Tag is already ${TAG}, nothing to update."
              exit 0
            fi

            git push origin --delete "$BRANCH" 2>/dev/null || true
            
            git checkout -b "$BRANCH"
            git add values.yaml
            git commit -m "update tag to ${TAG}"
            git push -u origin "$BRANCH"
            gh pr create \
              --repo arunkaousula9421/helm-chart-repo \
              --base main \
              --head "$BRANCH" \
              --title "Update tag to ${TAG}" \
              --body "Automated update"